-- https://school.programmers.co.kr/learn/courses/30/lessons/131534#qna
WITH DF AS (
SELECT COUNT(USER_ID) AS CNT
FROM USER_INFO
WHERE YEAR(JOINED)=2021)
SELECT 
    YEAR(ONLINE_SALE.SALES_DATE) AS YEAR,
    MONTH(ONLINE_SALE.SALES_DATE) AS MONTH,
    COUNT(DISTINCT(ONLINE_SALE.USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(ONLINE_SALE.USER_ID))*1.0/DF.CNT ,1) AS PURCHASED_RATIO
FROM USER_INFO 
JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
JOIN DF ON 1=1
WHERE YEAR(USER_INFO.JOINED) =2021
GROUP BY YEAR(ONLINE_SALE.SALES_DATE), MONTH(ONLINE_SALE.SALES_DATE)
ORDER BY YEAR(ONLINE_SALE.SALES_DATE), MONTH(ONLINE_SALE.SALES_DATE)
