-- https://school.programmers.co.kr/learn/courses/30/lessons/157339
SELECT 
    CAR.CAR_ID,
    CAR.CAR_TYPE,
    ROUND((1-(PLAN.DISCOUNT_RATE/100)) * 30 * CAR.DAILY_FEE ,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR 
JOIN (SELECT *
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
      WHERE DURATION_TYPE = '30일 이상'
     )PLAN
        ON PLAN.CAR_TYPE = CAR.CAR_TYPE 
JOIN (SELECT HISTORY_ID, CAR_ID, MAX(START_DATE) AS START_DATE, MAX(END_DATE) AS END_DATE
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
      GROUP BY CAR_ID
     ) HIST  ON HIST.CAR_ID = CAR.CAR_ID
WHERE CAR.CAR_TYPE IN ('세단','SUV')
AND HIST.END_DATE < '2022-11-01'
AND ROUND((1-(PLAN.DISCOUNT_RATE/100)) * 30 * CAR.DAILY_FEE ,0) >=500000 
AND ROUND((1-(PLAN.DISCOUNT_RATE/100)) * 30 * CAR.DAILY_FEE ,0) < 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC;