-- https://school.programmers.co.kr/learn/courses/30/lessons/131117
SELECT 
    PROD.PRODUCT_ID,
    PROD.PRODUCT_NAME,
    SUM(PROD.PRICE*ORD.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT PROD
JOIN FOOD_ORDER ORD ON ORD.PRODUCT_ID=PROD.PRODUCT_ID
WHERE DATE_FORMAT(ORD.PRODUCE_DATE,"%Y-%m")= '2022-05'
GROUP BY PROD.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;