-- https://school.programmers.co.kr/learn/courses/30/lessons/131124
WITH DF AS (SELECT 
    MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(MEMBER_ID) DESC
LIMIT 1)
SELECT MEM.MEMBER_NAME, RE.REVIEW_TEXT, DATE_FORMAT(RE.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM DF
JOIN MEMBER_PROFILE MEM ON MEM.MEMBER_ID=DF.MEMBER_ID
JOIN REST_REVIEW RE ON MEM.MEMBER_ID=RE.MEMBER_ID
ORDER BY RE.REVIEW_DATE, RE.REVIEW_TEXT;