-- https://school.programmers.co.kr/learn/courses/30/lessons/133027
WITH DF AS (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
FROM FIRST_HALF
GROUP BY FLAVOR
UNION
SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
FROM JULY
GROUP BY FLAVOR)
SELECT FLAVOR 
FROM DF
GROUP BY FLAVOR
ORDER BY SUM(TOTAL) DESC
LIMIT 3;
