-- https://school.programmers.co.kr/learn/courses/30/lessons/144856
SELECT
    AUTHOR.AUTHOR_ID,
    AUTHOR.AUTHOR_NAME,
    BOOK.CATEGORY,
    SUM(BOOK_SALES.SALES * BOOK.PRICE) AS TOTAL_SALES
FROM BOOK
JOIN AUTHOR ON BOOK.AUTHOR_ID=AUTHOR.AUTHOR_ID
JOIN BOOK_SALES ON BOOK.BOOK_ID=BOOK_SALES.BOOK_ID
WHERE BOOK_SALES.SALES_DATE >= '2022-01-01' AND BOOK_SALES.SALES_DATE < '2022-02-01'
GROUP BY AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID ASC, BOOK.CATEGORY DESC;