-- https://school.programmers.co.kr/learn/courses/30/lessons/131532#qna
SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    INFO.GENDER AS GENDER,
    COUNT(DISTINCT(INFO.USER_ID)) AS USERS
FROM ONLINE_SALE SALE
JOIN USER_INFO INFO ON INFO.USER_ID = SALE.USER_ID and INFO.GENDER IS NOT NULL
GROUP BY DATE_FORMAT(SALES_DATE,'%Y-%m'),INFO.GENDER
ORDER BY 1,2,3;