-- https://school.programmers.co.kr/learn/courses/30/lessons/164668
SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES 
FROM  USED_GOODS_BOARD A
LEFT JOIN USED_GOODS_USER B ON B.USER_ID=A.WRITER_ID
WHERE A.STATUS = 'DONE' 
GROUP BY B.USER_ID 
HAVING SUM(A.PRICE)>=700000
ORDER BY SUM(A.PRICE) ASC;