-- https://school.programmers.co.kr/learn/courses/30/lessons/284527
SELECT 
    SUM(GR.SCORE) AS SCORE,
    EM.EMP_NO AS EMP_NO,
    EM.EMP_NAME AS EMP_NAME,
    EM.POSITION AS POSITION,
    EM.EMAIL AS EMAIL
FROM HR_EMPLOYEES EM
JOIN HR_GRADE GR ON GR.EMP_NO = EM.EMP_NO
GROUP BY EM.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;