-- https://school.programmers.co.kr/learn/courses/30/lessons/131116#qna
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT PI
WHERE PI.PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT WHERE PI.CATEGORY=CATEGORY)
AND CATEGORY IN ('과자','국','김치','식용유')
ORDER BY MAX_PRICE DESC;