-- https://school.programmers.co.kr/learn/courses/30/lessons/133026
SELECT B.INGREDIENT_TYPE, SUM(A.TOTAL_ORDER) FROM FIRST_HALF A
LEFT JOIN ICECREAM_INFO B ON A.FLAVOR=B.FLAVOR
GROUP BY B.INGREDIENT_TYPE 
ORDER BY A.TOTAL_ORDER ASC;