-- https://school.programmers.co.kr/learn/courses/30/lessons/299310
WITH DF AS (
    SELECT 
        YEAR(EC.DIFFERENTIATION_DATE) AS YEAR,
        MAX(EC.SIZE_OF_COLONY) AS MAX_COL
    FROM ECOLI_DATA EC
    GROUP BY YEAR(EC.DIFFERENTIATION_DATE)
)
SELECT 
    YEAR(ECO.DIFFERENTIATION_DATE) AS YEAR,
    ABS(DF.MAX_COL - ECO.SIZE_OF_COLONY) AS YEAR_DEV,
    ECO.ID 
FROM DF
RIGHT JOIN ECOLI_DATA ECO ON DF.YEAR = YEAR(ECO.DIFFERENTIATION_DATE)
ORDER BY 1, 2;