-- https://school.programmers.co.kr/learn/courses/30/lessons/301650
select FIR.ID
FROM ECOLI_DATA FIR
LEFT JOIN (SELECT ID, PARENT_ID FROM ECOLI_DATA) SEC ON FIR.PARENT_ID= SEC.ID
LEFT JOIN (SELECT ID, PARENT_ID FROM ECOLI_DATA) THR ON SEC.PARENT_ID =THR.ID
WHERE FIR.PARENT_ID IS NOT NULL
AND SEC.PARENT_ID IS NOT NULL
AND THR.PARENT_ID IS NULL
ORDER BY FIR.ID;