-- https://school.programmers.co.kr/learn/courses/30/lessons/273712
SELECT INFO.ITEM_ID,INFO.ITEM_NAME,INFO.RARITY
FROM ITEM_INFO INFO
LEFT JOIN ITEM_TREE TREE ON INFO.ITEM_ID=TREE.PARENT_ITEM_ID
WHERE TREE.ITEM_ID IS NULL
order by INFO.ITEM_ID DESC;
