-- https://school.programmers.co.kr/learn/courses/30/lessons/131114
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') as FREEZERYN from FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE '%창고_경기%'
ORDER BY WAREHOUSE_ID ASC;