-- https://school.programmers.co.kr/learn/courses/30/lessons/273711
SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
FROM (SELECT ITEM_TREE.ITEM_ID AS ITEM_ID
    FROM (SELECT ITEM_ID, ITEM_NAME, RARITY
    FROM ITEM_INFO
    WHERE RARITY = 'RARE') DF
    JOIN ITEM_TREE ON ITEM_TREE.PARENT_ITEM_ID=DF.ITEM_ID
    ORDER BY ITEM_TREE.ITEM_ID) ID
JOIN ITEM_INFO ON ITEM_INFO.ITEM_ID=ID.ITEM_ID
ORDER BY ITEM_INFO.ITEM_ID DESC
;